### ISSUE TITLE
What does the underlyingType() represent?

### ISSUE THREAD

**Issue by othercorey** [phpDocumentor/TypeResolver#116]
I'm looking at converting the previous ClassString types I added to psuedo-types. However, I'm not sure how PsuedoType is expected to be used.

`underlyingType()` returns an empty instance of the type, but `False_` and `True_` already extend that type. What is the use case for `underlyingType()`? Is it always supposed to be an empty instance of a type? I'm curious why a type string isn't used instead.

For `ClassString` which represents a string, but also provides an FQSEN if the class-string includes one, would `underlyingType` be `new String()`?

Should psuedo-types always extend the underlying type?

**Comment by mvriel** [comment]
UnderlyingType is intended for pseudo-types to represent what type or primitive they really are. PseudoTypes are userland constructs that are in reality a primitive (ClassString is a string for example) and UnderlyingType helps parsers, resolvers and analyzers to better validate that type because they can match it to a value. 

For example, an analyzer that would want to check if the pseudotype False is a boolean would need to keep track of a list of all pseudotypes and their real types.

This feature has not been applied to all PseudoTypes yet; that is something we intend to expand on or accept Pull Requests to help us with

**Comment by othercorey** [comment]
How about this question specifically?

> Should psuedo-types always extend the underlying type?

**Comment by mvriel** [comment]
The PseudoTypes classes are designed to extend an underlying type; this mechanism was introduced so that consumers can use instanceof calls to check for the actual type and by choosing which class to instanceof-check you can define your own specificity.

**Comment by othercorey** [comment]
Ok, I can do that.

I'm still a little confused why `underlyingType` exists if you can always do an `instanceof` check on the PsuedoType itself since it extends the same underlying type.

**Comment by jaapio** [comment]
In case of a `String` this is very clear. but what about a `Collection` with a certain key and value? Types can be very complex :-)

**Comment by othercorey** [comment]
Ok, so psuedo types can just implement `PsuedoType` without having to extend the underlying type. That should work for me.

**Comment by mvriel** [comment]
Also: you can do an instanceof; but not use the toString; underlyingType exposes that too

**Comment by mvriel** [comment]
> Ok, so psuedo types can just implement PsuedoType without having to extend the underlying type. That should work for me.

If at all possible; I would prefer it to extend if it has a real world counterpart; such as String for ClassString; mixed would be more difficult but since recently it is a real type
