### ISSUE TITLE
Versions >=0.1.2 require @dev dependency

### ISSUE THREAD

**Issue by pamil** [phpDocumentor/TypeResolver#12]
Can we use stable, tagged versions instead of these `@dev` ones?

**Comment by scato** [comment]
I think the real question is: what will it take to declare TypeResolver as stable?

If we are waiting for PSR-5 to clear, it can be a while.

If it's something in the code base, maybe @mvriel can make a list. I'm sure there are quite some people who use this library who'd be happy to help. ;)

**Comment by shochdoerfer** [comment]
Any help needed to make this happen?

**Comment by mvriel** [comment]
I have just removed the last dev dependency and the library is tagged with a new release (0.1.8). The library is stable but before going 1.0 I'd prefer to fix the last issues that are in the tracker currently. Because I have too many projects active currently I need to divide my time so any PR that helps further this goal is appreciated of course.
