### ISSUE TITLE
ContextFactory ignores use statements when using traits

### ISSUE THREAD

**Issue by shochdoerfer** [phpDocumentor/TypeResolver#13]
I ran into the following issue with the TypeResolver. I have the following trait defined:
```php
namespace ResolverDemo\Traits;

use ResolverDemo\Services\MyService;

trait SampleTrait
{
    /**
     * @return MyService
     */
    public static function getService()
    {
        return new MyService();
    }
}
```
The trait is used in the following class. It is important to realize that the class resides in a different namespace.
```php
namespace ResolverDemo;

use ResolverDemo\Traits\SampleTrait;

class Config
{
    use SampleTrait;
}
```

If I try to lookup the "MyService" class in the context of the Config class, the TypeResolver fails to detect the "correct" namespace. The following code returns \ResolverDemo\MyService instead of \ResolverDemo\Services\MyService.

```php
use phpDocumentor\Reflection\FqsenResolver;
use phpDocumentor\Reflection\Types\ContextFactory;
use ResolverDemo\Config;

$fqsenResolver = new FqsenResolver();
$contextFactory = new ContextFactory();

$context = $contextFactory->createFromReflector(new ReflectionClass(Config::class));
var_dump((string) $fqsenResolver->resolve('MyService', $context));
```

**Comment by mvriel** [comment]
I have looked into the issue and found that TypeResolver's behaviour is as expected. 

TypeResolver attempts to mimic PHP's behaviour as close as possible when it comes to type resolution and in your example you have provided the Config class (and thus it's file) as Context; but the MyService class can indeed not be resolved because the `use` statement is in the file of the SampleTrait.

I had to verify whether this is indeed the expected behaviour (it may have been that PHP does some magic import of `use` statements when provided in traits; but it was not) using the following scenario:

**MyService.php**
```php
<?php
namespace ResolverDemo\Services;

class MyService {}
```

**SampleTrait.php**
```php
<?php

namespace ResolverDemo\Traits;

include('MyService.php');

use ResolverDemo\Services\MyService;

trait SampleTrait
{
    /**
     * @return MyService
     */
    public static function getService()
    {
        return new MyService();
    }
}
```

**Config.php**
```php
<?php
namespace ResolverDemo;

include('SampleTrait.php');

use ResolverDemo\Traits\SampleTrait;

class Config
{
    use SampleTrait;

    public function __construct()
    {
        new MyService();
    }
}

new Config();
```

When I execute `Config.php` using php then I receive the following error:

```
$> php Config.php
PHP Fatal error:  Class 'ResolverDemo\MyService' not found in /Users/mvriel/Copy/Projects/OSS/phpDocumentor/TypeResolver/Config.php on line 12
PHP Stack trace:
PHP   1. {main}() /Users/mvriel/Copy/Projects/OSS/phpDocumentor/TypeResolver/Config.php:0
PHP   2. ResolverDemo\Config->__construct() /Users/mvriel/Copy/Projects/OSS/phpDocumentor/TypeResolver/Config.php:16

Fatal error: Class 'ResolverDemo\MyService' not found in /Users/mvriel/Copy/Projects/OSS/phpDocumentor/TypeResolver/Config.php on line 12

Call Stack:
    0.0004     243568   1. {main}() /Users/mvriel/Copy/Projects/OSS/phpDocumentor/TypeResolver/Config.php:0
    0.0006     246296   2. ResolverDemo\Config->__construct() /Users/mvriel/Copy/Projects/OSS/phpDocumentor/TypeResolver/Config.php:16
```

Meaning that the implementation as done by TypeResolver is correct. 

### Solution

There are various ways to resolve your use-case:

1. Accept php's behaviour and add a `use` statement to Config.php
2. Use the SampleTrait trait to base your Context from
3. Change the ContextFactory to become an interface and add your own implementation that builds a list of namespace aliases by recursively adding the `use` statements whenever a Trait use is encountered.

Option 3 is not consistent with the implementation of PHP and as such I would not want that to be a default option; but I could understand it if you would want it in a specific use-case; hence my suggestion to extract the ContextFactory to an interface so that you can implement a concrete implementation in your own project

**Comment by mvriel** [comment]
p.s. this did point out a nice place for an abstraction; the ContextFactory could anyhow benefit from being promoted to an interface and split into two concrete instances

**Comment by shochdoerfer** [comment]
Thanks @mvriel for the analysis. Totally makes sense as traits are compiler-assisted copy&paste blocks of code. So when you think about it it is clear why the imports are not "seen" in the class implementing the trait. 

To be fair I am not sure if it makes sense to provide a different logic than the default php way of the implementation. Thus I am not sure if the interface would really make sense (in this particular case).
