### ISSUE TITLE
No "false" and "true" as per phpDocumentor docs?

### ISSUE THREAD

**Issue by jesseschalken** [phpDocumentor/TypeResolver#14]
According to http://www.phpdoc.org/docs/latest/references/phpdoc/types.html, `false` and `true` are valid types in PHPDoc, but I can't find any representation in the classes implementing `phpDocumentor\Reflection\Type`. Is it missing?

Thanks

**Comment by jaapio** [comment]
True and false are resolved as boolean. Since they actually are. We won't add them as a type.

**Comment by jesseschalken** [comment]
`false|string` is not the same as `bool|string`. What if I want to document the fact that a function may only return `false` (eg in the case of failure, like many PHP builtins) but will never return `true`?

**Comment by voku** [comment]
I try to auto-generate my README (https://github.com/voku/portable-utf8/blob/master/build/generate_docs.php) and now my documentation has ```bool|string``` but in the code I use ```false|string```.  :-/ 

@jaapio Has the behavior changed in the last years, so that I can return the correct value?

**Comment by jaapio** [comment]
I'm reopening this issue because of an internal discussion about the handling of `pseudo` types. Since this library is used in so many packages we need to be careful with BC changes. Of course, there are many ways to ensure things won't break. 

I cannot say anything about a time path when we are introducing this feature. 

First thing we came up with was the introduction of a `False` class that would represent `False` and entends `Boolean`. But I personally dislike the ability to extend `Boolean`  and interface would be better so we can keep the implementations closed. 

We will not introduce all `pseudo` types as classes, some types like `bool` will be interpreted.
