### ISSUE TITLE
BUG: extends final class Array_

### ISSUE THREAD

**Issue by gorskimarcin96** [phpDocumentor/TypeResolver#148]
phpdocumentor/type-resolver/src/PseudoTypes/List_.php27: final class List_ extends Array_ implements PseudoType

I search bug: final class List_ extends **final** class Array_

**Comment by jaapio** [comment]
Are you sure you updated all you code? the `final` keyword was removed from the `Array_` class.

https://github.com/phpDocumentor/TypeResolver/blob/1.x/src/Types/Array_.php#L27

**Comment by jroszkiewicz** [comment]
> Are you sure you updated all you code? the `final` keyword was removed from the `Array_` class.
> 
> https://github.com/phpDocumentor/TypeResolver/blob/1.x/src/Types/Array_.php#L27

This happened when we install phpunit (9.5.11 or any new instance) via simple-phpunit from symfony/phpunit-bridge (from fresh directory of course)
I think it's related to something with wrong dependency, because when we add 

`<env name="SYMFONY_PHPUNIT_REQUIRE" value="phpdocumentor/type-resolver:1.5.1"/>`

all errors gone.
Really strange 🥸

**Comment by jroszkiewicz** [comment]
`root@7d00a7b57b87:/app# bin/phpunit -c phpunit.xml.dist
No composer.json found in the current directory, showing available packages from packagist.org
Creating a "phpunit/phpunit" project at "./phpunit-9.5.11-0"
Installing phpunit/phpunit (9.5.11)
Plugins have been disabled.
  - Downloading phpunit/phpunit (9.5.11)
  - Installing phpunit/phpunit (9.5.11): Extracting archive
Created project in /app/bin/.phpunit/phpunit-9.5.11-0
composer.json has been updated
No composer.lock file present. Updating dependencies to latest instead of installing from lock file. See https://getcomposer.org/install for more information.
Loading composer repositories with package information
Updating dependencies
Lock file operations: 36 installs, 0 updates, 0 removals
  - Locking doctrine/instantiator (1.4.0)
  - Locking myclabs/deep-copy (1.10.2)
  - Locking nikic/php-parser (v4.13.2)
  - Locking phar-io/manifest (2.0.3)
  - Locking phar-io/version (3.1.0)
  - Locking phpdocumentor/reflection-common (2.2.0)
  - Locking phpdocumentor/reflection-docblock (5.3.0)
  - Locking phpdocumentor/type-resolver (1.6.0)
  - Locking phpspec/prophecy (v1.15.0)
  - Locking phpspec/prophecy-phpunit (v2.0.1)
  - Locking phpunit/php-code-coverage (9.2.10)
  - Locking phpunit/php-file-iterator (3.0.6)
  - Locking phpunit/php-invoker (3.1.1)
  - Locking phpunit/php-text-template (2.0.4)
  - Locking phpunit/php-timer (5.0.3)
  - Locking sebastian/cli-parser (1.0.1)
  - Locking sebastian/code-unit (1.0.8)
  - Locking sebastian/code-unit-reverse-lookup (2.0.3)
  - Locking sebastian/comparator (4.0.6)
  - Locking sebastian/complexity (2.0.2)
  - Locking sebastian/diff (4.0.4)
  - Locking sebastian/environment (5.1.3)
  - Locking sebastian/exporter (4.0.4)
  - Locking sebastian/global-state (5.0.3)
  - Locking sebastian/lines-of-code (1.0.3)
  - Locking sebastian/object-enumerator (4.0.4)
  - Locking sebastian/object-reflector (2.0.4)
  - Locking sebastian/recursion-context (4.0.4)
  - Locking sebastian/resource-operations (3.0.3)
  - Locking sebastian/type (2.3.4)
  - Locking sebastian/version (3.0.2)
  - Locking symfony/deprecation-contracts (v3.0.0)
  - Locking symfony/phpunit-bridge (9.5.11.99)
  - Locking symfony/polyfill-ctype (v1.23.0)
  - Locking theseer/tokenizer (1.2.1)
  - Locking webmozart/assert (1.10.0)
Writing lock file
Installing dependencies from lock file
Package operations: 35 installs, 0 updates, 0 removals
  - Downloading myclabs/deep-copy (1.10.2)
  - Downloading phar-io/version (3.1.0)
  - Downloading phar-io/manifest (2.0.3)
  - Downloading phpdocumentor/reflection-common (2.2.0)
  - Downloading phpdocumentor/type-resolver (1.6.0)
  - Downloading sebastian/recursion-context (4.0.4)
  - Downloading sebastian/exporter (4.0.4)
  - Downloading sebastian/diff (4.0.4)
  - Downloading sebastian/comparator (4.0.6)
  - Downloading symfony/polyfill-ctype (v1.23.0)
  - Downloading webmozart/assert (1.10.0)
  - Downloading phpdocumentor/reflection-docblock (5.3.0)
  - Downloading doctrine/instantiator (1.4.0)
  - Downloading phpspec/prophecy (v1.15.0)
  - Downloading theseer/tokenizer (1.2.1)
  - Downloading sebastian/version (3.0.2)
  - Downloading nikic/php-parser (v4.13.2)
  - Downloading sebastian/lines-of-code (1.0.3)
  - Downloading sebastian/environment (5.1.3)
  - Downloading sebastian/complexity (2.0.2)
  - Downloading sebastian/code-unit-reverse-lookup (2.0.3)
  - Downloading phpunit/php-text-template (2.0.4)
  - Downloading phpunit/php-file-iterator (3.0.6)
  - Downloading phpunit/php-code-coverage (9.2.10)
  - Downloading phpunit/php-invoker (3.1.1)
  - Downloading phpunit/php-timer (5.0.3)
  - Downloading sebastian/cli-parser (1.0.1)
  - Downloading sebastian/code-unit (1.0.8)
  - Downloading sebastian/object-reflector (2.0.4)
  - Downloading sebastian/global-state (5.0.3)
  - Downloading sebastian/object-enumerator (4.0.4)
  - Downloading sebastian/resource-operations (3.0.3)
  - Downloading sebastian/type (2.3.4)
  - Downloading symfony/deprecation-contracts (v3.0.0)
  - Installing myclabs/deep-copy (1.10.2): Extracting archive
  - Installing phar-io/version (3.1.0): Extracting archive
  - Installing phar-io/manifest (2.0.3): Extracting archive
  - Installing phpdocumentor/reflection-common (2.2.0): Extracting archive
  - Installing phpdocumentor/type-resolver (1.6.0): Extracting archive
  - Installing sebastian/recursion-context (4.0.4): Extracting archive
  - Installing sebastian/exporter (4.0.4): Extracting archive
  - Installing sebastian/diff (4.0.4): Extracting archive
  - Installing sebastian/comparator (4.0.6): Extracting archive
  - Installing symfony/polyfill-ctype (v1.23.0): Extracting archive
  - Installing webmozart/assert (1.10.0): Extracting archive
  - Installing phpdocumentor/reflection-docblock (5.3.0): Extracting archive
  - Installing doctrine/instantiator (1.4.0): Extracting archive
  - Installing phpspec/prophecy (v1.15.0): Extracting archive
  - Installing theseer/tokenizer (1.2.1): Extracting archive
  - Installing sebastian/version (3.0.2): Extracting archive
  - Installing nikic/php-parser (v4.13.2): Extracting archive
  - Installing sebastian/lines-of-code (1.0.3): Extracting archive
  - Installing sebastian/environment (5.1.3): Extracting archive
  - Installing sebastian/complexity (2.0.2): Extracting archive
  - Installing sebastian/code-unit-reverse-lookup (2.0.3): Extracting archive
  - Installing phpunit/php-text-template (2.0.4): Extracting archive
  - Installing phpunit/php-file-iterator (3.0.6): Extracting archive
  - Installing phpunit/php-code-coverage (9.2.10): Extracting archive
  - Installing phpunit/php-invoker (3.1.1): Extracting archive
  - Installing phpunit/php-timer (5.0.3): Extracting archive
  - Installing sebastian/cli-parser (1.0.1): Extracting archive
  - Installing sebastian/code-unit (1.0.8): Extracting archive
  - Installing sebastian/object-reflector (2.0.4): Extracting archive
  - Installing sebastian/global-state (5.0.3): Extracting archive
  - Installing sebastian/object-enumerator (4.0.4): Extracting archive
  - Installing sebastian/resource-operations (3.0.3): Extracting archive
  - Installing sebastian/type (2.3.4): Extracting archive
  - Installing symfony/deprecation-contracts (v3.0.0): Extracting archive
  - Installing symfony/phpunit-bridge (9.5.11.99): Symlinking from ../../../vendor/symfony/phpunit-bridge
4 package suggestions were added by new dependencies, use `composer suggest` to see details.
Generating optimized autoload files
26 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
PHPUnit 9.5.11 by Sebastian Bergmann and contributors.

Testing
S..PHP Fatal error:  Class phpDocumentor\Reflection\PseudoTypes\List_ may not inherit from final class (phpDocumentor\Reflection\Types\Array_) in /app/bin/.phpunit/phpunit-9.5.11-0/vendor/phpdocumentor/type-resolver/src/PseudoTypes/List_.php on line 27

Fatal error: Class phpDocumentor\Reflection\PseudoTypes\List_ may not inherit from final class (phpDocumentor\Reflection\Types\Array_) in /app/bin/.phpunit/phpunit-9.5.11-0/vendor/phpdocumentor/type-resolver/src/PseudoTypes/List_.php on line 27`

**Comment by jroszkiewicz** [comment]
And with
`
<env name="SYMFONY_PHPUNIT_REQUIRE" value="phpdocumentor/type-resolver:1.5.1"/>
`

root@7d00a7b57b87:/app# bin/phpunit -c phpunit.xml.dist
No composer.json found in the current directory, showing available packages from packagist.org
Creating a "phpunit/phpunit" project at "./phpunit-9.5.11-0"
Installing phpunit/phpunit (9.5.11)
Plugins have been disabled.
  - Installing phpunit/phpunit (9.5.11): Extracting archive
Created project in /app/bin/.phpunit/phpunit-9.5.11-0
composer.json has been updated
composer.json has been updated
No composer.lock file present. Updating dependencies to latest instead of installing from lock file. See https://getcomposer.org/install for more information.
Loading composer repositories with package information
Updating dependencies
Lock file operations: 36 installs, 0 updates, 0 removals
  - Locking doctrine/instantiator (1.4.0)
  - Locking myclabs/deep-copy (1.10.2)
  - Locking nikic/php-parser (v4.13.2)
  - Locking phar-io/manifest (2.0.3)
  - Locking phar-io/version (3.1.0)
  - Locking phpdocumentor/reflection-common (2.2.0)
  - Locking phpdocumentor/reflection-docblock (5.3.0)
  - Locking phpdocumentor/type-resolver (1.5.1)
  - Locking phpspec/prophecy (v1.15.0)
  - Locking phpspec/prophecy-phpunit (v2.0.1)
  - Locking phpunit/php-code-coverage (9.2.10)
  - Locking phpunit/php-file-iterator (3.0.6)
  - Locking phpunit/php-invoker (3.1.1)
  - Locking phpunit/php-text-template (2.0.4)
  - Locking phpunit/php-timer (5.0.3)
  - Locking sebastian/cli-parser (1.0.1)
  - Locking sebastian/code-unit (1.0.8)
  - Locking sebastian/code-unit-reverse-lookup (2.0.3)
  - Locking sebastian/comparator (4.0.6)
  - Locking sebastian/complexity (2.0.2)
  - Locking sebastian/diff (4.0.4)
  - Locking sebastian/environment (5.1.3)
  - Locking sebastian/exporter (4.0.4)
  - Locking sebastian/global-state (5.0.3)
  - Locking sebastian/lines-of-code (1.0.3)
  - Locking sebastian/object-enumerator (4.0.4)
  - Locking sebastian/object-reflector (2.0.4)
  - Locking sebastian/recursion-context (4.0.4)
  - Locking sebastian/resource-operations (3.0.3)
  - Locking sebastian/type (2.3.4)
  - Locking sebastian/version (3.0.2)
  - Locking symfony/deprecation-contracts (v3.0.0)
  - Locking symfony/phpunit-bridge (9.5.11.99)
  - Locking symfony/polyfill-ctype (v1.23.0)
  - Locking theseer/tokenizer (1.2.1)
  - Locking webmozart/assert (1.10.0)
Writing lock file
Installing dependencies from lock file
Package operations: 35 installs, 0 updates, 0 removals
  - Downloading phpdocumentor/type-resolver (1.5.1)
  - Installing myclabs/deep-copy (1.10.2): Extracting archive
  - Installing phar-io/version (3.1.0): Extracting archive
  - Installing phar-io/manifest (2.0.3): Extracting archive
  - Installing phpdocumentor/reflection-common (2.2.0): Extracting archive
  - Installing phpdocumentor/type-resolver (1.5.1): Extracting archive
  - Installing sebastian/recursion-context (4.0.4): Extracting archive
  - Installing sebastian/exporter (4.0.4): Extracting archive
  - Installing sebastian/diff (4.0.4): Extracting archive
  - Installing sebastian/comparator (4.0.6): Extracting archive
  - Installing symfony/polyfill-ctype (v1.23.0): Extracting archive
  - Installing webmozart/assert (1.10.0): Extracting archive
  - Installing phpdocumentor/reflection-docblock (5.3.0): Extracting archive
  - Installing doctrine/instantiator (1.4.0): Extracting archive
  - Installing phpspec/prophecy (v1.15.0): Extracting archive
  - Installing theseer/tokenizer (1.2.1): Extracting archive
  - Installing sebastian/version (3.0.2): Extracting archive
  - Installing nikic/php-parser (v4.13.2): Extracting archive
  - Installing sebastian/lines-of-code (1.0.3): Extracting archive
  - Installing sebastian/environment (5.1.3): Extracting archive
  - Installing sebastian/complexity (2.0.2): Extracting archive
  - Installing sebastian/code-unit-reverse-lookup (2.0.3): Extracting archive
  - Installing phpunit/php-text-template (2.0.4): Extracting archive
  - Installing phpunit/php-file-iterator (3.0.6): Extracting archive
  - Installing phpunit/php-code-coverage (9.2.10): Extracting archive
  - Installing phpunit/php-invoker (3.1.1): Extracting archive
  - Installing phpunit/php-timer (5.0.3): Extracting archive
  - Installing sebastian/cli-parser (1.0.1): Extracting archive
  - Installing sebastian/code-unit (1.0.8): Extracting archive
  - Installing sebastian/object-reflector (2.0.4): Extracting archive
  - Installing sebastian/global-state (5.0.3): Extracting archive
  - Installing sebastian/object-enumerator (4.0.4): Extracting archive
  - Installing sebastian/resource-operations (3.0.3): Extracting archive
  - Installing sebastian/type (2.3.4): Extracting archive
  - Installing symfony/deprecation-contracts (v3.0.0): Extracting archive
  - Installing symfony/phpunit-bridge (9.5.11.99): Symlinking from ../../../vendor/symfony/phpunit-bridge
4 package suggestions were added by new dependencies, use `composer suggest` to see details.
Generating optimized autoload files
26 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
PHPUnit 9.5.11 by Sebastian Bergmann and contributors.

Testing (and here everything looks cool)

**Comment by jaapio** [comment]
If you project is a symfony project using PHPUnit, the autoloading will go wrong in some edge cases. This library is a dependency of both projects. 

I do expect your PHP loads the `Array_` class from the phpunit directory and the `List_` class from the vendor directory. The PHPUnit bridge is a pain for us. That's why we cannot use PHPUnit as normal composer dependency in this project for example. 

Glad you found the issue.

**Comment by RobinHoutevelts** [comment]
Adding the `SYMFONY_PHPUNIT_REQUIRE` with `phpdocumentor/type-resolver:1.5.1` fixed it for me

My `phpunit.xml` now contains:

```xml
<php>
    <ini name="error_reporting" value="-1"/>
    <!-- https://github.com/phpDocumentor/TypeResolver/issues/148#issuecomment-1005542099 -->
    <server name="SYMFONY_PHPUNIT_REQUIRE" value="phpdocumentor/type-resolver:1.5.1"/>
```

Thanks @jroszkiewicz

**Comment by jroszkiewicz** [comment]
@RobinHoutevelts best option is update main composer.lock to use type-resolver 1.6.0

`
composer update phpdocumentor/type-resolver
`

**Comment by waaghals** [comment]
> @RobinHoutevelts best option is update main composer.lock to use type-resolver 1.6.0
> 
> `composer update phpdocumentor/type-resolver`

I'm not sure this is the best option. Updating it only updates it in the lock file.
This means that if you were to add another package with requires phpdocumentor/type-resolver < 1.6.0 it will revert the update back to the lower version of 1.5.1, while Symfony's phpunit bridge will use 1.6.0. So you'll have the same problem again.

If you want to ensure that you do not install a lower version of a dependency, while you don't want it in in your dependencies. You should configure it in conflics of composer.json.
```json
    "conflict": {
        "phpdocumentor/type-resolver": "<1.6.0"
    },
```

Having said that, I think @RobinHoutevelts solution is better as you can leave a comment why the version was pinned.
