### ISSUE TITLE
TypeResolver resolve ?string|null|?boolean|?int as Nullable instead of Compound

### ISSUE THREAD

**Issue by steevanb** [phpDocumentor/TypeResolver#69]
Hi,

When i want to resolve a variable type, there is a little bug when it begin with `?`: it should return a `Compound` object, but it return a `Nullable` object, with `Compound` as realType. As you can see in example below, in `?string|null|?boolean` , `?boolean` is well parsed, cause it's not the first one.
```php
$typeResolver = new TypeResolver();
print_r($typeResolver->resolve('?string|null|?boolean'));
```
```php
phpDocumentor\Reflection\Types\Nullable Object
(
    [realType:phpDocumentor\Reflection\Types\Nullable:private] => phpDocumentor\Reflection\Types\Compound Object
        (
            [types:phpDocumentor\Reflection\Types\Compound:private] => Array
                (
                    [0] => phpDocumentor\Reflection\Types\String_ Object
                        (
                        )
                    [1] => phpDocumentor\Reflection\Types\Null_ Object
                        (
                        )
                    [2] => phpDocumentor\Reflection\Types\Nullable Object
                        (
                            [realType:phpDocumentor\Reflection\Types\Nullable:private] => phpDocumentor\Reflection\Types\Boolean Object
                                (
                                )
                        )
                )
        )
)
```

Another example, that works well, without `?` as first character:
```php
$typeResolver = new TypeResolver();
print_r($typeResolver->resolve('string|null|?boolean'));
```
```php
phpDocumentor\Reflection\Types\Compound Object
(
    [types:phpDocumentor\Reflection\Types\Compound:private] => Array
        (
            [0] => phpDocumentor\Reflection\Types\String_ Object
                (
                )
            [1] => phpDocumentor\Reflection\Types\Null_ Object
                (
                )
            [2] => phpDocumentor\Reflection\Types\Nullable Object
                (
                    [realType:phpDocumentor\Reflection\Types\Nullable:private] => phpDocumentor\Reflection\Types\Boolean Object
                        (
                        )
                )
        )
)
```

**Comment by jaapio** [comment]
The hard part about this is how we should interpret this. I remember a discussion about this in the PSR-5 context. 

I think from a usage perspective the following typehints are equal:

`?string|null|?boolean`
`string|null|?boolean`
`?string|null|boolean`
`?string|boolean`
`string|?boolean`
`string|null|boolean`

Since the `?` sign states that the passed value might be a `null` null is a valid value. There is no difference between a `null` that could have been a `string` or `boolean` value. 

Most important thing is that we need to be sure when we are resolving the types of `?string|null|boolean` the to string method of the resulting Compound type should be equal to the resolved type. And that it does mean the same thing that was resolved. It is unclear to me if this is the case at the moment. So I will add a test with this use-case to check that.
