### ISSUE TITLE
Unusable exceptions

### ISSUE THREAD

**Issue by razbakov** [phpDocumentor/TypeResolver#86]
I had to run `composer update` on my project to solve security issues and I got error which was difficult to triage.

### Steps to reproduce

- install latest https://github.com/api-platform/api-platform/
- create entity with some error code like `@return string?`
- run `composer update`

### Actual result

```
api_platform    | Script cache:clear returned with error code 1
api_platform    | !!  
api_platform    | !!   // Clearing the cache for the dev environment with debug                       
api_platform    | !!   // true                                                                        
api_platform    | !!  
api_platform    | !!  
api_platform    | !!  In FileLoader.php line 166:
api_platform    | !!                                                                                 
api_platform    | !!    A type is missing after a nullable character in . (which is being imported   
api_platform    | !!    from "/srv/api/config/routes/api_platform.yaml"). Make sure there is a load  
api_platform    | !!    er supporting the "api_platform" type.                                       
api_platform    | !!                                                                                 
api_platform    | !!  
api_platform    | !!  In TypeResolver.php line 251:
api_platform    | !!                                                  
api_platform    | !!    A type is missing after a nullable character  
```

### Expected result

- More details in exception with information about file and line where the error is found

**Comment by jaapio** [comment]
Hi, thanks for your report.

I'm sorry to hear that you had a long journey to find the error you had with parsing the types of your project.
If I look at the error report it is clear to me that there was some nullable sign found in the code that was not expected.
However I don't think we can solve this problem in this library since we don't have any context during the resolving of the the types. Only the namespace and imports are known.
If someone of api platform is able to help us digging into this we are open to help and review any submitted pr. But for now there is not much we can do without digging into api platforms code.

So please create an issue on that project as well, and reference this issue in your report to them. Maybe we can improve the user experience together.
Thanks in advance

**Comment by razbakov** [comment]
You probably right, that should be handled in api-platform.
